
spring:
  application:
    name: chatService
  datasource:
    url: jdbc:mysql://localhost:3308/mydb
    username: myuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4c366dc1f97220143c1d05418e4208ff
            client-secret: xFEhmSJ3LL3sMHo3ZXf4Hz7IVM6lAO7V
            scope:
              - profile_nickname
              - account_email
              - name
              - gender
              - birthday
              - phone_number
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  address: 0.0.0.0
  port: 8080